openapi: 3.0.0
info:
  title: Nuts Registry Admin API
  version: 1.0.0

paths:
  /health:
    get:
      summary: "More elaborate health check to conform the app is (probably) functioning correctly"
      description: "Returns the status in Spring Boot Health format."
      operationId: checkHealth
      responses:
        200:
          description: "Returned when the status is UP"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CheckHealthResponse"
        503:
          description: "Returned when the status is DOWN"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CheckHealthResponse"
  /web/diagnostics:
    get:
      summary: "Returns the node key diagnostics"
      operationId: diagnostics
      responses:
        200:
          description: "Diagnostics data."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Diagnostics"
  /web/network_topology:
    get:
      summary: "Returns the network as a graph model"
      operationId: networkTopology
      responses:
        200:
          description: "Network topology data"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/NetworkTopology"
components:
  schemas:
    CheckHealthResponse:
      required:
        - status
        - details
      properties:
        status:
          type: string
          description: Overall status derived from performed health checks. Values are "UP", "DOWN" and "UNKNOWN".
        details:
          type: object
          description: Map of the performed health checks and their results.
          additionalProperties:
            $ref: "#/components/schemas/HealthCheckResult"
    Diagnostics:
      required:
        - network
        - status
        - vcr
        - vdr
      properties:
        network:
          $ref: '#/components/schemas/Network'
        status:
          $ref: '#/components/schemas/Status'
        vcr:
          $ref: '#/components/schemas/VCR'
        vdr:
          $ref: '#/components/schemas/VDR'
    Network:
      type: object
      description: network and connection diagnostics
      required:
        - connections
        - state
      properties:
        connections:
          type: object
          required:
            - connected_peers_count
            - peer_id
          properties:
            connected_peers_count:
              type: integer
              description: "number of peers connected"
            peer_id:
              type: string
              description: "identifier generated at startup of the node"
        node_did:
          type: string
          description: "DID connected to the node."
        state:
          type: object
          description: "Key numbers of the DAG"
          required:
            - dag_lc_high
            - dag_xor
            - failed_events
            - stored_database_size_bytes
            - transaction_count
          properties:
            dag_lc_high:
              type: integer
              description: "highest LC value"
            dag_xor:
              type: string
              description: "XOR value of all transaction refs"
            failed_events:
              type: integer
              description: "number of failed internal events"
            stored_database_size_bytes:
              type: number
              description: "size of the DB in bytes"
            transaction_count:
              type: number
              description: "number of transactions on the network"
    Status:
      type: object
      description: "characteristics of running process"
      required:
        - git_commit
        - os_arch
        - software_version
        - uptime
      properties:
        git_commit:
          type: string
          description: "hash of latest commit in github used to build the current binary"
        os_arch:
          type: string
          description: "System architecture (arm,amd64, etc)"
        software_version:
          type: string
          description: "Github tag or branch"
        uptime:
          type: number
          description: "Nanoseconds of uptime"
    VCR:
      type: object
      description: "key numbers on credentials"
      required:
        - credential_count
        - issuer
        - verifier
      properties:
        credential_count:
          type: integer
          description: "total number of observed credentials"
        issuer:
          type: object
          description: "numbers on issued credentials"
          required:
            - issued_credentials_count
            - revoked_credentials_count
          properties:
            issued_credentials_count:
              type: integer
              description: "number of issued credentials from this node"
            revoked_credentials_count:
              type: integer
              description: "number of revoked credentials from this node"
        verifier:
          type: object
          required:
            - revocations_count
          properties:
            revocations_count:
              type: integer
              description: "total number of revocations in the network"
    VDR:
      type: object
      description: "key numbers on DID Documents"
      required:
        - conflicted_did_documents
        - did_documents_count
      properties:
        conflicted_did_documents:
          type: object
          description: "numbers on conflicted DID documents"
          required:
            - owned_count
            - total_count
          properties:
            owned_count:
              type: integer
              description: "number of conflicted documents that are under this node's control"
            total_count:
              type: integer
              description: "total number of conflicted documents"
        did_documents_count:
          type: integer
          description: "total number of DID Documents"
    NetworkTopology:
      required:
        - vertices
        - edges
        - peerID
      properties:
        peerID:
          type: string
          description: "own node's network ID"
        vertices:
          type: array
          description: "array of PeerIDs"
          items:
            type: string
        edges:
          description: "list of tuples (PeerID -> PeerID)"
          type: array
          items:
            type: array
            items:
              type: string
    HealthCheckResult:
      required:
        - status
      properties:
        status:
          type: string
          description: Status of the health check. Values are "UP", "DOWN" and "UNKNOWN".
        details:
          description: Details of the health check result.

